### ISSUE TITLE
Not working on LION

### ISSUE THREAD

**Issue by crowej** [tylerhall/MacSosumi#13]
accounts dont seem to connect on Lion, just left with the account name on the sidebar no devices.

**Comment by maxmcn** [comment]
Same problem here. Any fix?

**Comment by tylerhall** [comment]
It's fixed now. You can grab the source from here on GitHub, or there's a compiled binary [available here](http://clickontyler.com/sosumi/).

**Comment by maxmcn** [comment]
Thanks for the fix.
