### ISSUE TITLE
Sosumi don't show devices anymore

### ISSUE THREAD

**Issue by eidos85** [tylerhall/MacSosumi#15]
Sosumi don't show any devices anymore, in the console debug return "Could not login to FMIP" but it worked with the same account until yesterday.
Thank you

**Comment by bleedingedge** [comment]
PHP class is not working anymore. Apple must have changed something.

**Comment by bleedingedge** [comment]
It seems Apple switched off Version 1.3 of findmyiphone. In the PHP class I just changed Code to 1.4 and it is working again.

**Comment by eidos85** [comment]
Right! i changed it and now it works again!
Thank you

**Comment by tylerhall** [comment]
Fixed.
