### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by dak180** [tylerhall/MacSosumi#16]
As you can see from

![screenshot](http://imgbin.org/images/7902.png)

none of my accounts are working and I cannot even delete them to try again.

(version 1.3.3)

**Comment by tylerhall** [comment]
Odd. I just tried a fresh install and it's working for me. Does clicking the Refresh button help? Try wiping your Preferences. Delete this file:

~/Library/Preferences/com.clickontyler.macsosumi.plist

**Comment by dak180** [comment]
None of that helps (I am running 10.6 without flash if that makes any difference), it just keeps saying `Could not login to FMIP` in the console logs.

**Comment by tylerhall** [comment]
Are you using your full iCloud address to sign in? i.e.,
username@me.com, not username.

On Fri, May 4, 2012 at 12:35 PM, dak180
reply@reply.github.com
wrote:

**Comment by dak180** [comment]
Yes, I am.
