### ISSUE TITLE
Add refresh timer adjustment

### ISSUE THREAD

**Issue by tylerhall** [tylerhall/MacSosumi#8]
User should be able to adjust how frequently FMIP is polled - ideally on a device by device basis. Important since this affects battery life (considerably).

**Comment by mlaster** [comment]
It would be best if you use the value returned by the server (callbackIntervalInMS in the ServerContext dictionary).  That way you won't get throttled for hammering on the servers.

**Comment by tylerhall** [comment]
Good catch. I'll look into updating this.

**Comment by tylerhall** [comment]
Fixed.
